LOCAL_LOOKUP = {
    "nao": "",
    "demasiar": "demasiado",
    "reabertura": "reabrir",
    "resolução": "resolver",
    "resoluçao": "resolver",
    "resolucão": "resolver",
    "resolucao": "resolver",
    "solução": "resolver",
    "soluçao": "resolver",
    "solucão": "resolver",
    "solucao": "resolver",
    "resolvido": "resolver",
    "solucionar": "resolver",
    "respostar": "resposta",
    "responder": "resposta",
    "necessario": "necessidade",
    "horar": "hora",
    "maquinar": "maquina",
    "situação": "",
    "situacão": "",
    "situacao": "",
    "situaçao": "",
    "questão": "",
    "questao": "",
    "assunto":"",
    "caso":"",
    "casar":"",
    "ter":"",
    "haver":"",
    "ser":"",
    "estar":"",
    "fazer":"",
    "ficar":"",
    "dar":"",
    "un":""
}
LOCAL_NONSTOP = {
    "tempo": "tempo"
}
LOCAL_PREFIX = {
    "...": "",
    "asd": "",
    "asf": "",
    "afd": "",
    "qwe": "",
    "zxc": "",
    "aaa": "",
    "bbb": "",
    "ccc": "",
    "ddd": "",
    "eee": "",
    "fff": "",
    "ggg": "",
    "hhh": "",
    "iii": "",
    "jjj": "",
    "kkk": "",
    "lll": "",
    "mmm": "",
    "nnn": "",
    "ooo": "",
    "ppp": "",
    "qqq": "",
    "rrr": "",
    "sss": "",
    "ttt": "",
    "uuu": "",
    "vvv": "",
    "www": "",
    "xxx": "",
    "yyy": "",
    "zzz": ""
}
